### ISSUE TITLE
support non axis aligned lirs

### ISSUE THREAD

**Issue by lukasalexanderweber** [lukasalexanderweber/lir#5]
Arbitrary Orientation:

"To resolve this limitation, the solution is considered such that by
rotating the boundary of the shape in different directions, in each case the largest rectangle
is computed. Then, by comparing their area with each other, the largest rectangle is
specified in the desired direction."

https://stackoverflow.com/questions/9041681/opencv-python-rotate-image-by-x-degrees-around-specific-point

**Comment by biggeR-data** [comment]
Hi, awesome project! Is this described feature already integrated? I checked the source and it doesn't seem to be the case.

**Comment by lukasalexanderweber** [comment]
Hi! Thanks :) No, it is not implemented yet.
