### ISSUE TITLE
support multiple contours

### ISSUE THREAD

**Issue by lukasalexanderweber** [lukasalexanderweber/lir#6]
return one LIR per contour

https://github.com/lukasalexanderweber/lir/blob/main/lir_within_outline.py line 23

**Comment by hansrajro** [comment]
Is there any way that draw Largest Interior Rectangle in multiple shapes in one picture only.Like given below picture contains 2 shapes. when i'm trying to run the test on this file its throw an error.
![images (2)](https://user-images.githubusercontent.com/98589131/155455250-e90cc871-65a9-4bac-abfa-c98ffe186b9c.png)


Thank You

**Comment by hansrajro** [comment]
@lukasalexanderweber

**Comment by lukasalexanderweber** [comment]
@hansrajro thanks for reaching out! 

I updated the functionality and you can find the according test in 
https://github.com/lukasalexanderweber/lir/blob/main/tests/test_lir_with_multiple_outlines.py

It results in 

https://github.com/lukasalexanderweber/lir/blob/main/readme_imgs/sample5.png

**Comment by hansrajro** [comment]
thanks @lukasalexanderweber

**Comment by hansrajro** [comment]
![mvp](https://user-images.githubusercontent.com/98589131/155563008-1e3ed35b-94b4-458b-b71a-eb987c6b75fa.png)
but when i'm trying to do the same for this picture, its throwing error.
trying to for loop in the test_multiple_shapes function. can you help me out here where i'm doing wrong?
thanks in advance 
    def test_multiple_shapes(self):
        cells = cv.imread("two_shapes.png", 0)

        outlines = list(lir.get_outlines(cells))
        for i in range(len(outlines)):
            rect_i = lir.largest_interior_rectangle(cells, outlines[i])
            # rect2 = lir.largest_interior_rectangle(cells, outlines[1])

            # np.testing.assert_array_equal(rect_i, np.array(rect_i))
            # np.testing.assert_array_equal(rect2, np.array(rect2))

        # # PLOT
            cells = cv.cvtColor(cells, cv.COLOR_GRAY2RGB)
            start_point = tuple(rect_i[:2])
            end_point = tuple(rect_i[:2] + rect_i[2:] - 1)
            image = cv.rectangle(cells, start_point, end_point, (0, 0, 255), 1)
            # start_point = tuple(rect2[:2])
            # end_point = tuple(rect2[:2] + rect2[2:] - 1)
            # image = cv.rectangle(image, start_point, end_point, (0, 0, 255), 1)
        cv.imwrite("rect1.png", image)

**Comment by lukasalexanderweber** [comment]
You want the rectangles from the inner white areas?

**Comment by hansrajro** [comment]
and yes i want to draw rectangles in  inner white areas. 
Thanks @lukasalexanderweber

**Comment by lukasalexanderweber** [comment]
First let me share the code to plot outlines and lirs:

```
        cells = cv.imread("complex.png", 0)
        image = cv.cvtColor(cells, cv.COLOR_GRAY2RGB)

        outlines = list(lir.get_outlines(cells))
        
        # plot outlines (green):
        for outline in outlines:
            for x, y in zip(*outline):
                image[y, x, :] = np.array([0, 255, 0])
        
        # create and plot lir (red)
        for outline in outlines:
            rect = lir.largest_interior_rectangle(cells, outline)
            start_point = tuple(rect[:2])
            end_point = tuple(rect[:2] + rect[2:] - 1)
            image = cv.rectangle(image, start_point, end_point, (0, 0, 255), 1)
        
        cv.imwrite("result.png", image)
```

Here some sample result:

![rect](https://user-images.githubusercontent.com/32765578/155856860-ebc65d7e-b428-4219-a35c-e2288d61c310.png)

In your case the problem also lies within cv.findContours(). The algorithm combines multiple rectangles into one outline. You have to play around with the settings. Yout image looks like it might come from GIS? Maybe the contours could be build based on the polygon information. Please let me know.

![rect2](https://user-images.githubusercontent.com/32765578/155856867-4af602bc-90d5-41ec-9848-60f7e3f14f22.png)

**Comment by hansrajro** [comment]
@lukasalexanderweber  yeah image came from GIS. So what can be done to resolve this issue?

**Comment by hansrajro** [comment]
@lukasalexanderweber  is there any way to calculate area of drawn rectangle ?
Thanks

**Comment by lukasalexanderweber** [comment]
could you share the shapefile or geojson?

**Comment by hansrajro** [comment]
@lukasalexanderweber , i don't have the geojson.
but suppose area of highlighted rectangle is X sq meters , then what will be the area of other rectangles.
![result123](https://user-images.githubusercontent.com/98589131/155985315-570f4b03-c8b5-4443-8fbb-545924967e6d.png)

**Comment by lukasalexanderweber** [comment]
`lir.largest_interior_rectangle ` returns `np.array([x ,y, width, height]) ` so `rect[2]*rect[3]` will give you the area

**Comment by hansrajro** [comment]
@lukasalexanderweber  thanks ,
this is the image i need to draw rectangles 
![out](https://user-images.githubusercontent.com/98589131/155995245-38943004-fd7a-40e2-a142-c71df4944028.jpg)

**Comment by hansrajro** [comment]
is there any way to draw rectangle in remaining white space recursively upto certain area of rectangle  ? @lukasalexanderweber 
![result](https://user-images.githubusercontent.com/98589131/156167694-06a304f0-f9b2-4429-b4a1-f9ed9444fd92.png)

**Comment by lukasalexanderweber** [comment]
Yeah just make the detected rectangles black (0) and run the lir-algorithm again.

`img[y:y+height, x:x + width] = 0` should du it

Make a copy of the image before the for loop and draw the detected rectangles (upto certain area) on it

**Comment by hansrajro** [comment]
@lukasalexanderweber  thanks for helping out.


here what i'm trying is this... 
but how to come out of recursion , i'm using counter for that but better way of doing is height or width or rectangle to stop recursion. can you suggest some changes to make that happen ?


areas = []
counter = 0
cells = cv.imread("area_cropped.png", 0)


def test_multiple_shapes(cells, counter):
    image = cv.cvtColor(cells, cv.COLOR_GRAY2RGB)

    outlines = list(lir.get_outlines(cells))

    # plot outlines (green):
    for outline in outlines:
        for x, y in zip(*outline):
            image[y, x, :] = np.array([0, 255, 0])

    # create and plot lir (red)

    for outline in outlines:
        rect = lir.largest_interior_rectangle(cells, outline)
        area = (rect[2] * rect[3])
        start_point = tuple(rect[:2])
        end_point = tuple(rect[:2] + rect[2:] - 1)
        x = int(rect[0] + rect[2] / 2)
        y = int(rect[1] + rect[3] / 2)
        if area > 5:
            areas.append(area)
            image = cv.rectangle(image, start_point, end_point, (0, 255, 0), 1)
            image[rect[1]:rect[1] + rect[3], rect[0]:rect[0] + rect[2]] = 0
        else:
            continue
        # image1 = cv.putText(image,area,(x,y), cv.FONT_HERSHEY_SIMPLEX, 0.2, (36,255,12))
    counter = counter + 1
    x = ran.randint(0, 9)
    image_name = 'result_' + str(x) + ".png"
    cv.imwrite(image_name, image)

    cells = cv.imread(image_name, 0)
    if counter < 3:
        test_multiple_shapes(cells, counter)
    else:
        return

**Comment by hansrajro** [comment]
@lukasalexanderweber  Hi, 
and If we want to create fixed width horizontal rectangle instead of largest rectangle. Where should i need to look ?
Thanks

**Comment by hansrajro** [comment]
@lukasalexanderweber if i want to draw first formed rectangle not the biggest span rectangle .
largest_rectangle_indices = np.where(areas == np.amax(areas))
what change can be made in this line ?
Thanks

**Comment by hansrajro** [comment]
here is the shape in which horizontal fixed height rectangle i need to make.
![mvp2](https://user-images.githubusercontent.com/98589131/157003715-d90670b9-96f9-448c-b3d3-0a78afce2c3e.png)

and here is the rectangle drawn after first iteration.
![result_1](https://user-images.githubusercontent.com/98589131/157003906-f62bf0df-3a10-4f13-9dbc-63808dbb96b7.png)


but i want these rectangle to start either from top or from bottom.
how to do this?
if you get some time to look into this, it will be grate help to me.
Thanks @lukasalexanderweber

**Comment by lukasalexanderweber** [comment]
first formed rectangle not the biggest span rectangle

Can you make a sketch of what you mean?

**Comment by hansrajro** [comment]
![imageedit_7_8927391860](https://user-images.githubusercontent.com/98589131/157204399-377e6240-a826-4151-9ddc-f0a45a24cabb.png)
 like this image I want fixed width(height) horizontal rectangle drawn either from top of  shape or bottom of shape.
but in lir it gives largest rectangle in given outline.
Thanks @lukasalexanderweber

**Comment by lukasalexanderweber** [comment]
Hey, I think this script can't help you with that, sorrry

**Comment by hansrajro** [comment]
Thanks Lukasalexanderweber/Lir for looking iinto the issue.

**Comment by hansrajro** [comment]
Anyways Thanks @lukasalexanderweber for looking into the issue.

**Comment by hansrajro** [comment]
is there any similar library which can handle this kind of problem?

**Comment by hansrajro** [comment]
or is there any way to draw all possible rectangle in one shape at a time then move to next shape and draw all possible rectangle. 
Right now this script draw one rectangle per shape only. 
So like we draw biggest rectangle in first shape , then need to draw next biggest rectangle in same shape till its cover full shape. then i need to move second shape and do the same thing and cover all shapes

**Comment by RGuven** [comment]
@hansrajro Hi, 
Could you able to find any solution that fits your problem ?
